Add support for `cookie_secure: auto`
scheb/2fa pull request #108
Opened 2021-09-24 12:39 UTC by wouterj

**Description**

This adds support for `cookie_secure: auto`. Symfony supports this value for the session and remember me cookies. It enables setting the secure flag only when the request was secure. This makes it very easy to have the most secure configuration that works in production (secure) and locally (not-secure).

2021-09-24 16:19 UTC, scheb requested changes
Thanks for adding this! Looks good, two small adjustments on the tests and we can merge.

2021-09-24 16:19 UTC, scheb commented on tests/Security/TwoFactor/Trusted/TrustedCookieResponseListenerTest.php
> +    public function onKernelResponse_cookieSecureAuto_secureRequest(): void
Can we rename please? `onKernelResponse_cookieSecureAutoOnSecureRequest_setSecureCookie`

2021-09-24 16:19 UTC, scheb commented on tests/Security/TwoFactor/Trusted/TrustedCookieResponseListenerTest.php
> +    public function onKernelResponse_cookieSecureAuto_unsecureRequest(): void
Can we rename please? `onKernelResponse_cookieSecureAutoOnUnsecureRequest_setUnsecureCookie`

2021-09-25 10:53 UTC, wouterj commented
Thanks, fixed the test names!

2021-09-25 10:58 UTC, merged